<a href="https://colab.research.google.com/github/AnjiLakshmi12/6thSem-ML-Lab/blob/main/1BM24CS401_Lab_4_Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Load dataset
data = pd.read_csv("/content/iris.csv.csv")

X = data.drop("species", axis=1)
y = data["species"]

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Train model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Results
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9666666666666667
Confusion Matrix:
 [[11  0  0]
 [ 0  8  1]
 [ 0  0 10]]


In [7]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Load dataset
data = pd.read_csv("/content/petrol_consumption.csv")

# Display first rows
print(data.head())

# Features and target
X = data.drop("Petrol_Consumption", axis=1)
y = data["Petrol_Consumption"]

# Split dataset (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create Regression Tree model
model = DecisionTreeRegressor()

# Train the model
model.fit(X_train, y_train)

# Predict test data
y_pred = model.predict(X_test)

# Calculate evaluation metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

# Display results
print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)

   Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   
1         9.0            4092            1250                         0.572   
2         9.0            3865            1586                         0.580   
3         7.5            4870            2351                         0.529   
4         8.0            4399             431                         0.544   

   Petrol_Consumption  
0                 541  
1                 524  
2                 561  
3                 414  
4                 410  
Mean Absolute Error (MAE): 87.7
Mean Squared Error (MSE): 16435.9
Root Mean Squared Error (RMSE): 128.2025740771222


In [9]:
# Import libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Load dataset
data = pd.read_csv("/content/drug.csv.csv")

# Display first rows
print(data.head())

# Convert categorical data to numerical for the target variable 'letter'
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# The original code tried to encode 'Sex', 'BP', 'Cholesterol' which are not in this dataset.
# The 'letter' column is the actual target and is categorical.
data['letter_encoded'] = le.fit_transform(data['letter'])

# Features and target
# X should drop the original 'letter' column and the new 'letter_encoded' if we don't want to use it as a feature
# The target `y` will be `letter_encoded`
X = data.drop([col for col in data.columns if col in ["letter", "letter_encoded"]], axis=1) # Drop original 'letter' and the encoded one from features
y = data["letter_encoded"]

# Split dataset (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create model
model = DecisionTreeClassifier()

# Train model
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

  letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  xybar  \
0      T     2     8      3       5      1     8    13      0      6      6   
1      I     5    12      3       7      2    10     5      5      4     13   
2      D     4    11      6       8      6    10     6      2      6     10   
3      N     7    11      6       6      3     5     9      4      6      4   
4      G     2     1      3       1      1     8     6      6      6      6   

   x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0      10       8      0       8      0       8  
1       3       9      2       8      4      10  
2       3       7      3       7      3       9  
3       4      10      6      10      2       8  
4       5       9      1       7      5      10  
Accuracy: 0.88525
Confusion Matrix:
 [[140   0   1   0   1   0   2   1   1   0   0   1   0   0   1   0   0   1
    0   0   0   0   0   0   0   0]
 [  0 128   0   4   0   2   2   3   1   0   0   1   0   1   0   0   3   2
    2