<a href="https://colab.research.google.com/github/AnjiLakshmi12/6thSem-ML-Lab/blob/main/%E2%80%9C1BM24CS401_Lab_1_DataProcessing_ipynb%E2%80%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

uploaded = files.upload()


Saving house.csv to house.csv


In [ ]:
import pandas as pd

# Load CSV file from Colab environment
df = pd.read_csv("/content/house.csv")

# Display first 5 rows
df.head()


ID  No_Pation Gender  AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL  \
0  502      17975      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
1  735      34221      M   26   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6   
2  420      47975      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
3  680      87656      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
4  504      34223      M   33   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4   

    BMI CLASS  
0  24.0     N  
1  23.0     N  
2  24.0     N  
3  24.0     N  
4  21.0     N

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   ID         1000 non-null   int64  
 1   No_Pation  1000 non-null   int64  
 2   Gender     1000 non-null   object 
 3   AGE        1000 non-null   int64  
 4   Urea       1000 non-null   float64
 5   Cr         1000 non-null   int64  
 6   HbA1c      1000 non-null   float64
 7   Chol       1000 non-null   float64
 8   TG         1000 non-null   float64
 9   HDL        1000 non-null   float64
 10  LDL        1000 non-null   float64
 11  VLDL       1000 non-null   float64
 12  BMI        1000 non-null   float64
 13  CLASS      1000 non-null   object 
dtypes: float64(8), int64(4), object(2)
memory usage: 109.5+ KB


In [ ]:
df.describe()


ID     No_Pation          AGE         Urea           Cr  \
count  1000.000000  1.000000e+03  1000.000000  1000.000000  1000.000000   
mean    340.500000  2.705514e+05    53.528000     5.124743    68.943000   
std     240.397673  3.380758e+06     8.799241     2.935165    59.984747   
min       1.000000  1.230000e+02    20.000000     0.500000     6.000000   
25%     125.750000  2.406375e+04    51.000000     3.700000    48.000000   
50%     300.500000  3.439550e+04    55.000000     4.600000    60.000000   
75%     550.250000  4.538425e+04    59.000000     5.700000    73.000000   
max     800.000000  7.543566e+07    79.000000    38.900000   800.000000   

             HbA1c         Chol           TG          HDL          LDL  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      8.281160     4.862820     2.349610     1.204750     2.609790   
std       2.534003     1.301738     1.401176     0.660414     1.115102   
min       0.900000     0.000000     0.300000     0.200000     0.300000   
25%       6.500000     4.000000     1.500000     0.900000     1.800000   
50%       8.000000     4.800000     2.000000     1.100000     2.500000   
75%      10.200000     5.600000     2.900000     1.300000     3.300000   
max      16.000000    10.300000    13.800000     9.900000     9.900000   

              VLDL          BMI  
count  1000.000000  1000.000000  
mean      1.854700    29.578020  
std       3.663599     4.962388  
min       0.100000    19.000000  
25%       0.700000    26.000000  
50%       0.900000    30.000000  
75%       1.500000    33.000000  
max      35.000000    47.750000

In [ ]:
df.isnull().sum()[df.isnull().sum() > 0]



Series([], dtype: int64)

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving adult.csv to adult.csv


In [ ]:
import pandas as pd

# Load CSV file from Colab environment
df1 = pd.read_csv("/content/adult.csv")

# Display first 5 rows
df1.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [ ]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler, StandardScaler




In [ ]:
df.isna().sum()


age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [ ]:
#(b) Handling Categorical Data
# Identify categorical columns
cat_cols_diabetes = df.select_dtypes(include='object').columns
cat_cols_diabetes


Index(['workclass', 'education', 'marital-status', 'occupation',
       'relationship', 'race', 'gender', 'native-country', 'income'],
      dtype='object')

In [ ]:
# Label Encoding
le = LabelEncoder()

for col in cat_cols_diabetes:
    df[col] = le.fit_transform(df[col])


In [ ]:
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1

df = df[~((df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR))).any(axis=1)]
df


age  workclass  fnlwgt  education  educational-num  marital-status  \
8       24          4  369667         15               10               4   
24      25          4  205947          9               13               2   
34      26          4   43311         11                9               0   
39      20          4  257509         11                9               4   
55      21          4  110677         15               10               4   
...    ...        ...     ...        ...              ...             ...   
48808   22          4  203715         15               10               4   
48809   31          4  292592         11                9               2   
48827   37          4  198216          7               12               0   
48836   22          4  310152         15               10               4   
48839   58          4  151910         11                9               6   

       occupation  relationship  race  gender  capital-gain  capital-loss  \
8               8             4     4       0             0             0   
24             10             0     4       1             0             0   
34              4             4     4       0             0             0   
39              3             3     4       1             0             0   
55              1             3     4       0             0             0   
...           ...           ...   ...     ...           ...           ...   
48808           1             3     4       1             0             0   
48809           7             5     4       0             0             0   
48827          13             1     4       0             0             0   
48836          11             1     4       1             0             0   
48839           1             4     4       0             0             0   

       hours-per-week  native-country  income  
8                  40              39       0  
24                 40              39       0  
34                 40              39       0  
39                 40              39       0  
55                 40              39       0  
...               ...             ...     ...  
48808              40              39       0  
48809              40              39       0  
48827              40              39       0  
48836              40              39       0  
48839              40              39       0  

[7491 rows x 15 columns]

In [ ]:
#DATA TRANSFORMATION – Diabetes Dataset
minmax = MinMaxScaler()
df_minmax = minmax.fit_transform(df)
df_minmax


array([[0.1372549 , 0.        , 0.94861359, ..., 0.        , 0.        ,
        0.        ],
       [0.15686275, 0.        , 0.51223289, ..., 0.        , 0.        ,
        0.        ],
       [0.17647059, 0.        , 0.0787415 , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.39215686, 0.        , 0.49162662, ..., 0.        , 0.        ,
        0.        ],
       [0.09803922, 0.        , 0.7899818 , ..., 0.        , 0.        ,
        0.        ],
       [0.80392157, 0.        , 0.36820221, ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
standard = StandardScaler()
df_standard = standard.fit_transform(df)
df_standard



array([[-0.98283071,  0.        ,  2.37486726, ...,  0.        ,
         0.        ,  0.        ],
       [-0.8951342 ,  0.        ,  0.37925799, ...,  0.        ,
         0.        ,  0.        ],
       [-0.80743769,  0.        , -1.60313823, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.15722388,  0.        ,  0.2850236 , ...,  0.        ,
         0.        ,  0.        ],
       [-1.15822372,  0.        ,  1.64942941, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.99885052,  0.        , -0.27940764, ...,  0.        ,
         0.        ,  0.        ]])

In [ ]:
# Replace '?' with NaN
df1.replace('?', np.nan, inplace=True)

# Check missing values
df1.isna().sum()


age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [ ]:
for col in df1.columns:
    if df1[col].isna().sum() > 0:
        df1[col].fillna(df1[col].mode()[0], inplace=True)


In [ ]:
# Identify categorical columns
cat_cols_adult = df1.select_dtypes(include='object').columns
cat_cols_adult


Index([], dtype='object')

In [ ]:
# Label Encoding
for col in cat_cols_adult:
    df1[col] = le.fit_transform(df1[col])


In [ ]:
Q1 = df1.quantile(0.25)
Q3 = df1.quantile(0.75)
IQR = Q3 - Q1

df1 = df1[~((df1 < (Q1 - 1.5 * IQR)) | (df1 > (Q3 + 1.5 * IQR))).any(axis=1)]
df1


age  workclass  fnlwgt  education  educational-num  marital-status  \
8       24          3  369667         15               10               4   
24      25          3  205947          9               13               2   
34      26          3   43311         11                9               0   
35      65          3  191846         11                9               2   
39      20          3  257509         11                9               4   
...    ...        ...     ...        ...              ...             ...   
48808   22          3  203715         15               10               4   
48809   31          3  292592         11                9               2   
48827   37          3  198216          7               12               0   
48836   22          3  310152         15               10               4   
48839   58          3  151910         11                9               6   

       occupation  relationship  race  gender  capital-gain  capital-loss  \
8               7             4     4       0             0             0   
24              9             0     4       1             0             0   
34              3             4     4       0             0             0   
35              9             0     4       1             0             0   
39              2             3     4       1             0             0   
...           ...           ...   ...     ...           ...           ...   
48808           0             3     4       1             0             0   
48809           6             5     4       0             0             0   
48827          12             1     4       0             0             0   
48836          10             1     4       1             0             0   
48839           0             4     4       0             0             0   

       hours-per-week  native-country  income  
8                  40              38       0  
24                 40              38       0  
34                 40              38       0  
35                 40              38       0  
39                 40              38       0  
...               ...             ...     ...  
48808              40              38       0  
48809              40              38       0  
48827              40              38       0  
48836              40              38       0  
48839              40              38       0  

[8059 rows x 15 columns]

In [ ]:
#DATA TRANSFORMATION – Adult Income Dataset
#(a) Min-Max Scaling
df1_minmax = minmax.fit_transform(df1)
df1_minmax


array([[0.1372549 , 0.        , 0.94895505, ..., 0.        , 0.        ,
        0.        ],
       [0.15686275, 0.        , 0.51241728, ..., 0.        , 0.        ,
        0.        ],
       [0.17647059, 0.        , 0.07876984, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.39215686, 0.        , 0.49180358, ..., 0.        , 0.        ,
        0.        ],
       [0.09803922, 0.        , 0.79026616, ..., 0.        , 0.        ,
        0.        ],
       [0.80392157, 0.        , 0.36833475, ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
df1_standard = standard.fit_transform(df1)
df1_standard


array([[-0.94700625,  0.        ,  2.36715397, ...,  0.        ,
         0.        ,  0.        ],
       [-0.86182568,  0.        ,  0.37701534, ...,  0.        ,
         0.        ,  0.        ],
       [-0.77664511,  0.        , -1.59994646, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.16034114,  0.        ,  0.28303928, ...,  0.        ,
         0.        ,  0.        ],
       [-1.11736739,  0.        ,  1.64370479, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.94913307,  0.        , -0.27984467, ...,  0.        ,
         0.        ,  0.        ]])